import type { Metadata } from "next";
import { Cormorant } from "next/font/google";
import "./globals.css";

const cormorantInfant = Cormorant({
  weight: ['400', '700'],
  variable: "--font-cormorant_infant",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Н+Н",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorantInfant.variable}`}>
        {children}
      </body>
    </html>
  );
}
